version: '3.8'

services:
  sga-cow:
    image: sga-cow:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sga-cow
    restart: unless-stopped
    ports:
      - "9899:9899"  # Web端口
    volumes:
      - ./config.json:/app/config.json:ro  # 只读挂载配置文件
      - ./logs:/app/logs
      - ./tmp:/app/tmp
    # 移除所有环境变量，完全使用config.json配置
      
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:9899/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    networks:
      - sga-cow-network

networks:
  sga-cow-network:
    driver: bridge

volumes:
  logs:
  tmp:
